name: Deploy Frontend React
on: [push]
jobs:
  Build Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Enter to frontend
        env: 
            NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
            NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
        run: |
          cd ./Frontend
          npm run build
          npx netlify-cli deploy --dir=dist prod
