name: Build Java Spring Boot with Gradle

on:
  push:
    branches:
      - feature/compile-java
  pull_request:
    branches:
      - feature/compile-java

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16'

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          node-version: '16'

      - name: Grant execute permission to gradlew
        run: chmod +x ./Backend/TaskManager/gradlew

      - name: Build with Gradle
        run: ./Backend/TaskManager/gradlew
